# Generated by Django 5.2.1 on 2026-02-03 12:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_courseenrollment_module_currency_and_more'),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenttransaction',
            name='module',
            field=models.ForeignKey(blank=True, help_text='Null for subscription payments', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='content.module'),
        ),
    ]
