# Generated by Django 5.2.1 on 2026-03-31 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_alter_paymenttransaction_module'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenttransaction',
            name='payment_method',
            field=models.CharField(choices=[('STRIPE', 'Stripe'), ('PAYPAL', 'PayPal'), ('LEMONSQ', 'Lemon Squeezy'), ('FREE', 'Free Enrollment')], default='STRIPE', max_length=10),
        ),
    ]
