# Generated by Django 5.2.1 on 2026-06-03 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0002_alter_quiz_passing_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='explanation',
            field=models.TextField(blank=True, default='', help_text='Shown to the learner AFTER they submit an attempt — never in the pre-answer quiz payload.'),
        ),
    ]
