# Generated by Django 5.2.1 on 2026-03-31 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_tutor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionplan',
            name='features',
            field=models.JSONField(default=dict, help_text='Dictionary of features included'),
        ),
        migrations.AlterUniqueTogether(
            name='subscriptionplan',
            unique_together={('name', 'billing_period')},
        ),
    ]
