# Generated by Django 5.2.1 on 2026-04-09 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_tutor', '0002_alter_subscriptionplan_features_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='lemon_squeezy_variant_id',
            field=models.CharField(blank=True, help_text='Lemon Squeezy variant ID for checkout', max_length=50, null=True),
        ),
    ]
