# Generated by Django 5.2.1 on 2026-04-11 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_tutor', '0003_subscriptionplan_lemon_squeezy_variant_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='lemon_squeezy_subscription_id',
            field=models.CharField(blank=True, default='', help_text='Lemon Squeezy subscription ID for cancellation', max_length=50),
        ),
    ]
