# Generated by Django 5.2.1 on 2025-05-25 01:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Order in which the module appears')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='SubModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Order within the parent module')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submodules', to='content.module')),
            ],
            options={
                'ordering': ['module', 'order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('lesson_type', models.CharField(choices=[('READ', 'Reading Material'), ('VID', 'Video Content'), ('SIM', 'Interactive Simulation'), ('QUIZ', 'Quiz / Assessment'), ('PROB', 'Problem Solving Exercise'), ('AI', 'AI Tutor Session')], default='READ', max_length=4)),
                ('order', models.PositiveIntegerField(default=0, help_text='Order within the parent submodule')),
                ('text_content', models.TextField(blank=True, help_text='Text content for reading, problem description, etc.', null=True)),
                ('video_url', models.URLField(blank=True, help_text='URL for video content (e.g., YouTube, Vimeo)', null=True)),
                ('simulation_url', models.URLField(blank=True, help_text='URL for an interactive simulation', null=True)),
                ('ai_tutor_initial_prompt', models.TextField(blank=True, help_text='Initial prompt or context for the AI Tutor', null=True)),
                ('ai_tutor_config', models.JSONField(blank=True, help_text='Specific configuration for this AI tutor session', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submodule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='content.submodule')),
            ],
            options={
                'ordering': ['submodule', 'order', 'title'],
            },
        ),
    ]
