# Generated by Django 5.2.1 on 2025-07-06 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_profile_userlessonprogress'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_premium',
            field=models.BooleanField(default=False, help_text='Designates if the user has a premium subscription'),
        ),
    ]
