# Generated by Django 5.2.1 on 2026-02-03 11:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_profile_is_premium'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True, help_text='Set to False if enrollment is cancelled/refunded')),
            ],
            options={
                'ordering': ['-enrolled_at'],
            },
        ),
        migrations.AddField(
            model_name='module',
            name='currency',
            field=models.CharField(default='USD', help_text='Currency code (e.g., USD, EUR)', max_length=3),
        ),
        migrations.AddField(
            model_name='module',
            name='is_premium_only',
            field=models.BooleanField(default=False, help_text='If True, only premium users can access this course'),
        ),
        migrations.AddField(
            model_name='module',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Price of the course (0.00 for free courses)', max_digits=10),
        ),
        migrations.AddIndex(
            model_name='userlessonprogress',
            index=models.Index(fields=['user', 'lesson'], name='content_use_user_id_a57e22_idx'),
        ),
        migrations.AddField(
            model_name='courseenrollment',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='content.module'),
        ),
        migrations.AddField(
            model_name='courseenrollment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='courseenrollment',
            index=models.Index(fields=['user', 'module'], name='content_cou_user_id_6a681a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='courseenrollment',
            unique_together={('user', 'module')},
        ),
    ]
