# Generated by Django 5.2.1 on 2026-03-31 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_courseenrollment_module_currency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0, help_text='Order within the parent submodule'),
        ),
        migrations.AlterField(
            model_name='module',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0, help_text='Order in which the module appears'),
        ),
        migrations.AlterField(
            model_name='submodule',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0, help_text='Order within the parent module'),
        ),
    ]
