# Generated by Django 5.2.1 on 2026-04-02 00:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_alter_lesson_order_alter_module_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='bunny_video_id',
            field=models.CharField(blank=True, help_text='Bunny Stream video GUID (takes priority over video_url)', max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='LessonFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(help_text='Display name (e.g., lab_01.ipynb)', max_length=255)),
                ('bunny_file_path', models.CharField(help_text='Path in Bunny Storage (e.g., module-1/lab_01.ipynb)', max_length=500)),
                ('file_size', models.PositiveIntegerField(default=0, help_text='File size in bytes')),
                ('file_type', models.CharField(blank=True, help_text='File extension (e.g., .py, .ipynb)', max_length=50)),
                ('description', models.CharField(blank=True, help_text='Brief description of the file', max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='content.lesson')),
            ],
            options={
                'ordering': ['order', 'file_name'],
            },
        ),
    ]
