# Generated by Django 5.2.1 on 2026-04-09 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_lesson_bunny_video_id_lessonfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='lemon_squeezy_variant_id',
            field=models.CharField(blank=True, help_text='Lemon Squeezy variant ID for paid checkout', max_length=50, null=True),
        ),
    ]
